#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Convert-GeekCode
version:      0.51
version_from: lib/Convert/GeekCode.pm
installdirs:  site
requires:
    YAML:                          0
    Text::Wrap:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
